project/admin/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from sqlalchemy import asc, desc
from sqlalchemy.sql.functions import coalesce
import datetime
from ..models import Admin, Biog, Work, Skills, Contact
from ..forms import AdminRegistrationForm, WorkForm, BiogForm, SkillsForm, ChangeActiveUser
from ..extensions import db


def choices_list_orderer(id):
    """In SelectField, the preloading of data is overruled by the list of choices. This queries the database to produce a list of tuples where the inputted id will be at the top of the list, and therefore the default. 

    Args:
        id (int): The biog id of name that should at the 0th index of the list

    Returns:
        List of tuples: Where tuples are (id, name) where the desired pre-loaded biog_id is the de-facto default.
    """
    raw_choices =  [(biog.id, biog.name) for biog in Biog.query.all()]
    list_of_choices = [raw_choices.pop(index) for index, tup in enumerate(raw_choices) if tup[0] == id]
    list_of_choices.extend(raw_choices)
    return list_of_choices

def active_user_generator():
    """Generates the active user as defined on the dashboard

    Returns:
        Object: Object of the model Biog
    """
    active_user = Biog.query.filter_by(active=1).first()
    return active_user

#Implementation of sqlalchemy's coalesce was from: http://progblog10.blogspot.com/2014/06/handling-null-values-in-sqlalchemy.html
def active_user_orderer():
    """Queries the database to produce a list of tuples where the current active user is at the top of the list, and therefore the default. 

    Returns:
        List of Tuples: Where tuples are (id, name)
    """
    return [(x.id, x.name) for x in Biog.query.order_by(asc(coalesce(Biog.active, 2)))]

admin = Blueprint('admin', __name__, url_prefix='/admin')

#The blueprint login restriction idea is from: https://michaelabrahamsen.com/posts/enforcing-login-on-all-flask-blueprint-routes/
@admin.before_request
@login_required
def restricted_view(): 
    pass

@admin.errorhandler(401)
def unauthorised(e):
    flash('You must be logged in to access the admin area')
    return redirect(url_for('public.login')), 401

@admin.errorhandler(500)
def servererror(e):
    flash('There has been an error. Please try again')
    return(redirect(url_for('admin.biog')))

@admin.route('/', methods=['GET', 'POST'])
def dashboard():
    active_user = active_user_generator()
    form = ChangeActiveUser()
    form.biog_id.choices = active_user_orderer()
    contacts = Contact.query.filter_by(biog_id=active_user.id).order_by(desc(Contact.id)).all()

    if form.validate_on_submit():
        #Check if there's an active user currently then to remove them as active:
        if Biog.query.filter_by(active=1).first():
            active_user_generator()
            active_user.active = None
            flash(f'{active_user.name}\'s portfolio is no longer being displayed')
            db.session.commit()
        new_active = Biog.query.get_or_404(form.biog_id.data)
        new_active.active = True
        db.session.commit()
        flash(f'Webpage now showing {new_active.name}\'s portfolio!')
        return redirect(url_for('admin.dashboard'))
    return render_template('dash.html', contacts=contacts, form=form, active_user=active_user)

@admin.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    flash('You have been logged out!')
    return redirect(url_for('public.login'))

@admin.route('/admins', methods=['GET','POST'])
def admins():
    active_user = active_user_generator()
    admins = Admin.query.all()
    form = AdminRegistrationForm()
    if form.validate_on_submit():
        admin = Admin(name=form.name.data, email=form.email.data, password=form.password.data)
        db.session.add(admin)
        db.session.commit()
        flash('Registration successful')
        return redirect(url_for('admin.admins'))
    return render_template('admins.html', form=form, admins=admins, active_user=active_user)

#deleting forms adapted from flatplanet's code: https://github.com/flatplanet/flasker/blob/main/app.py
@admin.route('/admins/delete/<int:id>')
def delete_admin(id):
    current_id = current_user.id
    #The site can't be without an admin
    if  id > 1:
        admin = Admin.query.get_or_404(id)
        db.session.delete(admin)
        db.session.commit()
        if id == current_id:
            flash('You have deleted your own account')
            return redirect(url_for('public.home'))
        flash('Admin deleted')    
        return redirect(url_for('admin.admins'))
    else:
        flash('You can\'t delete the primary admin')
        return redirect(url_for('admin.admins'))

@admin.route('/biog', methods=['GET','POST'])
def biog():
    active_user = active_user_generator()
    biogs = Biog.query.all()
    form = BiogForm()
    if form.validate_on_submit():
        image_filename = image_data = cv_filename = cv_data = None
        image_file = request.files['image_file']
        if image_file and not Biog.allowed_file_img(image_file.filename):
            flash('Incorrect file type attached. Please only upload images that are .JPG, .JPEG or .PNG')
            return redirect(url_for('admin.biog'))

        image_filename = secure_filename(image_file.filename)
        image_data = image_file.read()
        image_mimetype = image_file.mimetype

        cv_file = request.files['cv_file']
        if cv_file and not Biog.allowed_file_cv(cv_file.filename):
            flash('Incorrect file type attached. Please only upload CVs in a PDF format')
            return redirect(url_for('admin.biog'))

        cv_filename = secure_filename(cv_file.filename)
        cv_data = cv_file.read()
      
        biog = Biog(name=form.name.data, email=form.email.data, area=form.area.data, blurb=form.blurb.data, github=form.github.data, linkedin=form.linkedin.data, twitter=form.twitter.data, image_filename=image_filename, image_data=image_data, image_mimetype = image_mimetype, cv_filename=cv_filename, cv_data=cv_data)
        db.session.add(biog)
        db.session.commit()
        flash(f'{biog.name} added!')
        return redirect(url_for('admin.biog'))
    return render_template('biog.html', form=form, biogs=biogs, active_user=active_user)

#Updating forms adapted from flatplanet's code: https://github.com/flatplanet/flasker/blob/main/app.py
@admin.route('biog/<int:id>', methods=['GET', 'POST'])
def biog_update(id):
    active_user = active_user_generator()
    form = BiogForm()
    biog_to_update = Biog.query.get_or_404(id)
    #preloading the form with the existing data that is to be edited
    form.name.data = biog_to_update.name
    form.email.data = biog_to_update.email
    form.area.data = biog_to_update.area
    form.blurb.data = biog_to_update.blurb
    form.github.data = biog_to_update.github
    form.linkedin.data = biog_to_update.linkedin
    form.twitter.data = biog_to_update.twitter
    
    #update labels
    form.submit.label.text = 'Update'
    if not biog_to_update.image_filename == '':
        form.image_file.label.text = 'You have already uploaded a picture. If you would like to update it, please upload a new picture of yourself.'
    if not biog_to_update.cv_filename == '':
        form.cv_file.label.text = 'You have already uploaded a CV. If you would like to update it, please upload a new CV.'    

    if request.method == 'POST':
        biog_to_update.name = request.form['name']
        biog_to_update.email = request.form['email']
        biog_to_update.area = request.form['area']
        biog_to_update.blurb = request.form['blurb']
        biog_to_update.github = request.form['github']
        biog_to_update.linkedin = request.form['linkedin']
        biog_to_update.twitter = request.form['twitter']
        
        if request.files['image_file']:
            image_file = request.files['image_file']
            if image_file and not Biog.allowed_file_img(image_file.filename):
                flash('Incorrect file type attached. Please only upload images that are .JPG, .JPEG or .PNG')
                return redirect(url_for('admin.biog_update', id=biog_to_update.id))
            biog_to_update.image_filename = secure_filename(image_file.filename)
            biog_to_update.image_data = image_file.read()
            biog_to_update.image_mimetype = image_file.mimetype
            
        if request.files['cv_file']:
            cv_file = request.files['cv_file']
            if cv_file and not Biog.allowed_file_cv(cv_file.filename):
                flash('Incorrect file type attached. Please only upload CVs in a PDF format')
                return redirect(url_for('admin.biog_update', id=biog_to_update.id))
            biog_to_update.cv_filename = secure_filename(cv_file.filename)
            biog_to_update.cv_data = cv_file.read()

        try: 
            db.session.commit()
            flash(f'Updated {biog_to_update.name}\'s profile')
            return redirect(url_for('admin.biog_update', id=biog_to_update.id))
        except:
            flash('Unable to update profile')
            return redirect(url_for('admin.biog_update', id=biog_to_update.id))
    return render_template('biog_update.html', form=form, biog_to_update=biog_to_update, active_user=active_user)

#deleting forms adapted from flatplanet's code: https://github.com/flatplanet/flasker/blob/main/app.py
@admin.route('/biog/delete/<int:id>')
def biog_delete(id):
    biog_to_delete = Biog.query.get_or_404(id)
    name = biog_to_delete.name
    Skills.query.filter_by(biog_id=id).delete()
    Work.query.filter_by(biog_id=id).delete()
    db.session.delete(biog_to_delete)
    db.session.commit()
    flash(f'{name} has been deleted')
    return redirect(url_for('admin.biog'))


@admin.route('/work', methods=['GET','POST'])
def work():
    active_user = active_user_generator()
    try:

project/templates/admins.html
{% extends "layout.html" %}
{% block heading%}
<h4 class = "my-4">Add an Admin</h4>
{% endblock %}
{% block content %}

{% if form.errors.items() %}
    <div class="container alert alert-warning alert-dismissible fade show" role="alert">
        <ul class="list-unstyled">
            {% for field, errors in form.errors.items() %}
              <li>Under '{{ form[field].label }}'': {{ ', '.join(errors) }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div class="shadow-sm p-3 mb-5 bg-body rounded w-75">
    <form method="POST" action="" novalidate>
        {{ form.csrf_token }}
        {{ form.name.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.name (class="form-control") }}<br>
        {{ form.email.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.email (class="form-control") }}<br>
        {{ form.password.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.password (class="form-control") }}<br>
        {{ form.confirm_password.label(class="form-label") }}<span class="required">*</span><br>
        {{ form.confirm_password (class="form-control") }}<br>

        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

{% block admin_secondary %}
<div class="container">
    <div class="shadow-sm p-3 mb-5 bg-body rounded">
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col" class="w-20">Admin's name</th>
                <th scope="col" class="w-60">Email</th>
                <th scope="col" class="w-20"></th>
                </tr>
            </thead>
            {% for admin in admins %}
                <tr> 
                    <th scope="row">{{ admin.name }}</th>
                    <td>{{ admin.email }}</td>
                    <td><a href= "{{ url_for('admin.delete_admin', id=admin.id) }}" class="link-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

project/templates/biog.html
{% extends "layout.html" %}

{% block heading%}
<h4 class = "my-4">Add a User</h4>
{% endblock %}

{% if form.errors.items() %}
    <div class="container alert alert-warning alert-dismissible fade show" role="alert">
        <ul class="list-unstyled">
            {% for field, errors in form.errors.items() %}
              <li>Under '{{ form[field].label }}'': {{ ', '.join(errors) }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% block content %}
<div class="shadow-sm p-3 mb-5 bg-body rounded w-75">
    <form method="POST" novalidate enctype="multipart/form-data" action="">    
        {{ form.csrf_token }}
        {{ form.name.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.name (class="form-control") }}<br>
        {{ form.email.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.email (class="form-control") }}<br>
        {{ form.area.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.area (class="form-control") }}<br>
        {{ form.blurb.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.blurb (class="form-control") }}<br>
        {{ form.github.label (class="form-label") }}<br>
        <span>www.github.com/</span>{{ form.github (class="form-control", id="addon-wrapping") }}<br>
        {{ form.linkedin.label (class="form-label") }}<br>
        <span>www.linkedin.com/</span>{{ form.linkedin (class="form-control") }}<br>
        {{ form.twitter.label (class="form-label") }} <small>(Leave out the @)</small><br>
        <span>www.twitter.com/</span>{{ form.twitter (class="form-control") }}<br>
        {{ form.image_file.label (class="form-label") }}<br>
        {{ form.image_file (class="form-control") }}<br>
        {{ form.cv_file.label (class="form-label") }}<br>
        {{ form.cv_file (class="form-control") }}<br>
        {{ form.submit(class="btn btn-primary") }}

    </form>
</div>
{% endblock %}
{% block admin_secondary %}
<div class="container">
    <div class="shadow-sm p-3 mb-5 bg-body rounded">
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col" class="w-25">Name</th>
                <th scope="col" class="w-25">Area</th>
                <th scope="col" class="w-25">Email</th>
                <th scope="col" class="w-25"></th>
                </tr>
            </thead>
            {% for biog in biogs %}
                <tr>
                    <th scope="row"><a href="{{ url_for('admin.biog_update', id=biog.id) }}" class="link-secondary">{{ biog.name }}</a></th>
                    <td>{{ biog.area }}</td>
                    <td>{{ biog.email }}</td>
                    <td><a href="{{ url_for('admin.biog_delete', id=biog.id) }}" class="link-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

project/templates/biog_update.html
{% extends "biog.html" %}
{% block heading%}
<h4 class = "my-4">Amend {{ biog_to_update.name }}'s Details</h4>
{% endblock %}

{% block content %} 
<button type="button" class="btn btn-secondary mb-4 back">Back</button>
<a class="btn btn-danger mb-4 ms-4" href="{{ url_for('admin.biog_delete', id=biog_to_update.id) }}" role="button">Delete</a>
{{ super() }}
{% endblock %}

{% block admin_secondary %}
{% endblock %}

project/templates/contact_me.html
{% extends "layout.html" %}
{% block heading %}
<div>
    <h4 class = "my-4">Contact me</h4>
    <p>If you would like to get in touch regarding an opportunity or project to get involved with, please contact me on the form below and I will get back to you as soon as I can.</p>
</div>
{% endblock %}
{% block content %}

{% if form.errors.items() %}
    <div class="container alert alert-warning alert-dismissible fade show" role="alert">
        <ul class="list-unstyled">
            {% for field, errors in form.errors.items() %}
              <li>Under '{{ form[field].label }}'': {{ ', '.join(errors) }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div class="shadow-sm p-3 mb-5 bg-body rounded">
    <form method="POST" action="{{ url_for('public.contact_me') }}" novalidate>
        {{ form.csrf_token }}
        {{ form.name.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.name (class="form-control") }}<br>       
        {{ form.email.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.email (class="form-control") }}<br>
        {{ form.organisation.label (class="form-label") }}<br>
        {{ form.organisation (class="form-control") }}<br>
        {{ form.comment.label (class="form-label") }}<span class="required">*</span><br>
        {{ form.comment (class="form-control") }}<br>
        {{ form.recaptcha (class="form-control") }}<br>
        {{ form.submit(class="btn btn-primary") }}

        {% if form.recaptcha.errors %} 
            <div class="container alert alert-warning alert-dismissible fade show" role="alert">
                <ul>
                    <li>'Recaptcha Failed. Please try again'<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></li>
                </ul>
            </div>
        {% endif %}
    </form>
</div>
{% endblock %}
{% block footer %}
{% include 'footer.html' %}
{% endblock %}

project/templates/dash.html
{% extends "layout.html" %}
{% block heading%}
<h4 class = "my-4">The website is live for {{ active_user.name }}!</h4>
{% endblock %}

{% block content %}


<div class="shadow-sm p-3 mb-5 bg-body rounded w-75">
  <form method="POST" action="">
      {{ form.csrf_token }}
      {{ form.biog_id.label (class="form-label") }}<br>
      {{ form.biog_id (class="form-control") }}<br>
      {{ form.confirmation (class="form-check-input") }}  {{ form.confirmation.label (class="form-check-label") }}<span class="required">*</span><br>
      {{ form.submit(class="btn btn-primary mt-3") }}
  </form>
</div>

{% endblock %}
{% block admin_secondary %}
{% if contacts|length %}
<div class="container">
  <div class="shadow-sm p-3 mb-5 bg-body rounded">
  {% for contact in contacts %}
    {% if loop.index < 6 %}
      <p>{{ contact.name }} (<a href="mailto:{{ contact.email }}" class="link-secondary">{{ contact.email }}</a>)
        {% if contact.organisation|length %}
          of {{ contact.organisation }}
        {% endif %} 
      messaged:</p>
      <p class="mb-4 border-bottom">{{ contact.comment }}</p>
    {% endif %}
  {% endfor %}
  </div>
{% endif %}
</div>
{% endblock %}

project/templates/footer.html
<footer class="navbar-expand-lg">
    <a class="" href="{{ url_for('public.login') }}">&copy;</a>
</footer>

project/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="card my-4 shadow-sm p-3 bg-body rounded">
    <h5 class="card-header text-white" id="card-header-background">{{active_user.name}}'s Portfolio</h5>
    <div class="container card-body">
        <div class="row align-items-center">
            <div class="col-md-4">
                {% if active_user.image_filename|length < 1 %}                
                    <img src="{{ url_for('static', filename='default_image.jpg') }}" alt="Default Profile Picture" class="img-thumbnail rounded mx-auto d-block">
                {% else %}
                    <img src="{{ url_for('public.image', id=active_user.id) }}" alt="{{ active_user.name}}'s Profile Picture" class="img-thumbnail rounded mx-auto d-block">
                {% endif %}
            </div>    
            <div class="col-md-8">
                <h4 class="card-title">About me</h4>
                <p class="card-text">{{ active_user.blurb }}</p>
            </div>
        </div>
        <!-- The links images were adapted from: https://mdbootstrap.com/docs/standard/navigation/footer/ -->
        <div class="row">
            <div class="col-2 text-end">
                {% if active_user.github != '' %}
                    <a
                    class="btn text-white btn-floating m-1"
                    style="background-color: #333333;"
                    href="https://www.github.com/{{ active_user.github }}"
                    role="button"
                    target="_blank"
                    rel="noreferrer noopener"
                    ><i class="bi bi-github"></i>
                    </a>
                {% endif %}
            </div>
            <div class="col-2">
                {% if active_user.linkedin != '' %}
                    <a
                    class="btn text-white btn-floating m-1"
                    style="background-color: #0082ca;"
                    href="https://www.linkedin.com/{{ active_user.linkedin }}"
                    role="button"
                    target="_blank"
                    rel="noreferrer noopener"
                    ><i class="bi bi-linkedin"></i>
                    </a>
                {% endif %}
            </div>
        </div>      
        <div class="row">
            <div class="col-2 text-end">
                {% if active_user.twitter != '' %}
                    <a
                    class="btn text-white btn-floating m-1"
                    style="background-color: #55acee;"
                    href="https://www.twitter.com/{{ active_user.twitter }}"
                    role="button"
                    target="_blank"
                    rel="noreferrer noopener"
                    ><i class="bi bi-twitter"></i>
                    </a>
                {% endif %}
            </div>            
            <div class="col-2">
                {% if active_user.cv_filename != '' %}
                <a
                class="btn text-white btn-floating m-1"
                style="background-color: #FF0000;"
                href="{{ url_for('public.download') }}"
                role="button"
                ><i class="bi bi-filetype-pdf"></i>
                </a>
                {% endif %}
            </div>        
        </div>
    </div>
</div>

<!-- Employment History -->
<div class="shadow-sm p-3 mb-5 bg-body rounded">
    <h4 class = "my-4" >Employment History</h4>
    <table class="table table-hover align-left">
        <thead>
            <tr>
            <th scope="col" class="w-25">Job Title</th>
            <th scope="col" class="w-25">Company</th>
            <th scope="col" class="w-20">From</th>
            <th scope="col" class="w-20">Until</th>
            <th scope="col" class="w-10"></th>
            </tr>
        </thead>
        {% for work in works %}
        <tr> 
            <td>{{ work.title }} </td>
            <td>{{ work.company }}</td>
            <td>{{ work.start.strftime('%B %Y') }}</td>
            <td>{% if work.end is not none %} 
                    {{ work.end.strftime('%B %Y') }}
                {% else %}
                    Present Day 
                {% endif %}</td>               
            <td>
               <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#moreInfo{{ work.id }}">More info
                </button>
            </td> 
        </tr>

        <!-- Modal -->
    <div class="modal fade" id="moreInfo{{ work.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">{{ work.title }} at {{ work.company }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ work.job_description }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
        {% endfor %}
    </table>
</div>

<!-- Skills -->

<div class="shadow-sm p-3 mb-5 bg-body rounded">
    <h4 class = "my-4" >Skills and Qualitifications</h4>
    <div class="container">
        <div class="row row-cols-auto justify-content-around">
        {% for skill in skills %}
            <div class="card my-3" style="width: 18rem;">
                <div class="card-body">
                <h5 class="card-title">{{ skill.skill }}</h5>
                <p class="card-text">{{ skill.skill_description }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

project/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ active_user.name }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- favicon generated on https://www.favicon.cc/ -->
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}"> 
    </head>
  <body>
    {% include 'navbar.html' %}
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="container alert alert-warning alert-dismissible fade show" role="alert">
          <ul class="list-unstyled">
            {% for message in messages %}
              <li>{{ message }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
    {% endwith %}

    <div class = "container">
      {% block heading%}
      {% endblock %}
      {% block content %} 
      {% endblock %}
    </div>

    {% block admin_secondary %}
    {% endblock %}
   
    {% block footer %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.3.slim.js" integrity="sha256-DKU1CmJ8kBuEwumaLuh9Tl/6ZB6jzGOBV/5YpNE2BWc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function(){
        $(".link-danger").click(function(){
          let confirmation = confirm('Are you sure you want to delete?')
          if (confirmation != true){
            event.preventDefault()
          };      
        });
      });

      $(document).ready(function(){
        $(".btn-danger").click(function(){
          let confirmation = confirm('Are you sure you want to delete?')
          if (confirmation != true){
            event.preventDefault()
          };      
        });
      });

      $(document).ready(function(){
        $(".back").click(function(){
          parent.history.back();
        });
      });
    </script>
  </body>
</html>

project/templates/login.html
{% extends "layout.html" %}

{% block heading%}
<h4 class = "my-4">Login</h4>
{% endblock %}

{% if form.errors.items() %}
    <div class="container alert alert-warning alert-dismissible fade show" role="alert">
        <ul class="list-unstyled">
            {% for field, errors in form.errors.items() %}
              <li>Under '{{ form[field].label }}'': {{ ', '.join(errors) }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% block content %}
<div class = "container">
        <div class="shadow p-3 mb-5 bg-body rounded">
                <form method="POST" novalidate>
                {{ form.csrf_token }}
                {{ form.email.label (class="form-label") }}<br>
                {{ form.email (class="form-control") }}<br>
                {{ form.password.label (class="form-label") }}<br>
                {{ form.password (class="form-control") }}<br>
                {{ form.remember_me.label (class="form-label") }} 
                {{ form.remember_me }}<br>
                {{ form.submit (class="btn btn-primary")}}
                </form>
        </div>
</div>
{% endblock %}

project/templates/skills_update.html
{% extends "skills.html" %}
{% block heading%}
<h4 class = "my-4">Amend a Skill or Qualification</h4>
{% endblock %}

{% block content %} 
<button type="button" class="btn btn-secondary mb-4 back">Back</button>
<a class="btn btn-danger mb-4 ms-4" href="{{ url_for('admin.skills_delete', id=skill_to_update.id) }}" role="button">Delete</a>
{{ super() }}
{% endblock %}

{% block admin_secondary %}
{% endblock %}

project/templates/work_update.html
{% extends "work.html" %}
{% block heading%}
<h4 class = "my-4">Amend Work History</h4>
{% endblock %}

{% block content %} 
<button type="button" class="btn btn-secondary mb-4 back">Back</button>
<a class="btn btn-danger mb-4 ms-4" href="{{ url_for('admin.work_delete', id=work_to_update.id) }}" role="button">Delete</a>
{{ super() }}
{% endblock %}

{% block admin_secondary %}
{% endblock %}